version: '3.8'
services:
  mysql:
    image: mysql:8.0.33
    restart: always
    container_name: grab_table_mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: 'grab_table'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: